name: Update README

on:
  schedule:
    - cron: "*/5 * * * *" # update tiap 5 menit
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Stats
        run: |
          curl -o stats.svg "https://github-readme-stats.vercel.app/api?username=Krisnaputra05&show_icons=true&theme=tokyonight&count_private=true&token=${{ secrets.YOUR_TOKEN }}"

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add stats.svg
          git commit -m "Update GitHub stats" || echo "No changes"
          git push
